##############################################################
- alias: Chào mừng Mạnh về nhà # 36000 : 10 tiếng
  trigger:
    - platform: state
      entity_id: sensor.trackphone
  condition: 
    condition: template
    value_template: >
      {{ trigger.to_state and trigger.from_state and
         (trigger.to_state.last_changed - trigger.from_state.last_changed).total_seconds() > 36000 }}  
  action:
    - service: tts.google_translate_say
      entity_id: media_player.phong_khach
      data_template:
        message: >
          {{ ("Chào mừng Mạnh đã về nhà",
              "Chào mừng Mạnh đã trở về",
              "Rất vui khi Mạnh về nhà"
              )|random }}
    - service: notify.notify
      data_template:
        message: >
          Chào mừng Mạnh đã về nhà
#################################################################
